services:
  vet:
    build:
      context: ./vet
      dockerfile: ./Dockerfile
    environment:
      - PG_HOST=${PG_HOST}
      - PG_USER=${PG_USER}
      - DATABASE_URL=postgres://${PG_USER}:${PG_PASSWORD}@${PG_HOST}/${PG_NAME}?schema=public
      - PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - microservices

  payment:
    build:
      context: ./payment
      dockerfile: Dockerfile
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - PORT=3002
    ports:
      - "3002:3002"
    networks:
      - microservices

  cart:
    build:
      context: ./cart
      dockerfile: docker/node/Dockerfile
    environment:
      - DATABASE_URL=postgres://${PG_USER}:${PG_PASSWORD}@${PG_HOST}/${PG_NAME}?schema=public
      - PORT=3003
    ports:
      - "3003:3003"
    depends_on:
      - postgres
    networks:
      - microservices

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - microservices

  postgres:
    image: postgres:13.16-alpine
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_NAME}
    volumes:
      - postgres_data:/data/db
    networks:
      - microservices

volumes:
  postgres_data:
    driver: local
networks:
  microservices:
    driver: bridge
