services:
  vet:
    build:
      context: .
      dockerfile: ./vet/Dockerfile
    environment:
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_USERNAME=${MONGO_USERNAME}
    ports:
      - "4000:4000"
    volumes:
      - ./vet:/vet

  database:
    container_name: mongo-db
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=mongodb
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
volumes:
  data:
    driver: local
