services:
  vet:
    build:
      context: ./vet
      dockerfile: ./Dockerfile
    environment:
      - DATABASE_URL=postgres://${PG_USER}:${PG_PASSWORD}@${PG_HOST}/${PG_NAME}?schema=public
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  payment:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - PORT=3002
    ports:
      - "3002:3002"

  cart:
    build:
      context: ./cart-service
      dockerfile: docker/node/Dockerfile
    environment:
      - DATABASE_URL=postgres://${PG_USER}:${PG_PASSWORD}@${PG_HOST}/${PG_NAME}?schema=public
      - PORT=3003
    ports:
      - "3003:3003"
    depends_on:
      - postgres

  kennel:
    build:
      context: .
      dockerfile: ./kennel/Dockerfile
      environment:
      - DATABASE_URL=${DATABASE_URL}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_USERNAME=${MONGO_USERNAME}
      ports:
      - "3004:3004"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  postgres:
    image: postgres:13.16-alpine
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_NAME}
    volumes:
      - postgres_data:/data/db

volumes:
  postgres_data:
    driver: local
