services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - '3000:3000'
    depends_on:
      - animal
    networks:
      - app_network

  animal:
    build:
      context: ./animal
    ports:
      - '3001:3001'
    environment:
      - DATABASE_URL=mongodb://mongo:27017/Animals
      - PORT=3001
    depends_on:
      - mongo
    networks:
      - app_network

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongo_data:
