services:
  # cart:
  #   build:
  #     context: .
  #     dockerfile: ./docker/node/Dockerfile
  #   environment:
  #     - MONGO_DATABASE=${MONGO_DATABASE}
  #     - MONGO_PASSWORD=${MONGO_PASSWORD}
  #     - MONGO_USERNAME=${MONGO_USERNAME}
  #   ports:
  #     - "4000:4000"
  #   volumes:
  #     - .:/app

  cart-db:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=mongodb
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db

volumes:
  data:
    driver: local
