version: '3.8'
services:
  app:
    build:
      context: .
    ports:
      - '3000:3000' # Port de l'application NestJS
    environment:
      - DATABASE_URL=mongodb://mongo:27017/Animals
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
